backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Description, name: description, widget: string }
      - file: "src/pages/services/index.md"
        label: "Services Page"
        name: "services"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "services-page",
            }
          - {
              label: "First row", name: "firstRow", widget: "object",
                fields: [
                  {label: "Left Column Text", name: "leftColText", widget: "markdown", required: false},
                  {label: "Right Column Text", name: "rightColImage", widget: "image", required: false},
                ]
            }
          - {
              label: "Second row", name: "secondRow", widget: "object",
                fields: [
                  {label: "Left Column Image", name: "leftColImage", widget: "image", required: false},
                  {label: "Right Column Text", name: "rightColText", widget: "markdown", required: false},

                ]
            }
          - {
              label: "Third row", name: "thirdRow", widget: "object",
                fields: [
                  {label: "Left Column Text", name: "leftColText", widget: "markdown", required: false},
                  {label: "Right Column Image", name: "rightColImage", widget: "image", required: false},
                ]
            }
          - {
              label: "Call To Action Text",
              name: "ctaText",
              widget: "string",
              required: false
            }
          - {
              label: "Button Label Text",
              name: "btnLabelText",
              widget: "string",
              required: false
            }            
          - {
              label: "Call To Action Button Text",
              name: "bottomCtaButtonText",
              widget: "string",
              required: false
            }                                          
      - file: "src/pages/documentation-helper/index.md"
        label: "Documentation Page"
        name: "documentation"
        fields:
          - {
            label: "Template Key",
            name: "templateKey",
            widget: "hidden",
            default: "documentation-page"
          }            
  - name: "details"
    label: "Details"
    folder: "src/pages/details"
    create: true
    slug: "{{slug}}"
    fields: 
      - {
        label: "Template Key",
        name: "templateKey",
        widget: "hidden",
        default: "detail-page"
        }
      - { label: "Title (Hyperlink for Home Page)", name: "title", widget: "string" }
      - { label: "Home Image Label", name: "homeImageLabel", widget: "string", required: false }
      - { label: "Shoot Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false}
      - { label: "Gallery", name: "galleryImages", widget: "list", 
            field: { label: "Image", name: "src", widget: "image", required: false }
        }
